# standard container build workflow for the org
name: Build Container Image
on:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read
  packages: write
  
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup node 12
      uses: actions/setup-node@v3
      with:
        node-version: '12'
        cache: 'npm'

    - name: Install dependencies
      run: |
        npm install --silent

    - name: build site
      run:  npm run build

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Container Registry
      uses: docker/login-action@v2 
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: build and push
      id: build-image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository }}:${{ github.event.pull_request.head.sha || github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
